### ISSUE TITLE
TravisCI failure not replicated in local tests

### ISSUE THREAD

**Issue by ealtenho** [angular/dom-interceptor#1]
https://travis-ci.org/angular/dom-interceptor

There are errors occurring in the TravisCI build that I cannot replicate locally in karma in either Firefox or Chrome. 

@btford, how should I approach debugging this?

**Comment by btford** [comment]
> NS_ERROR_XPC_BAD_CONVERT_JS: Could not convert JavaScript argument

Oh this is neat.

Do some research and if you can't find anything, we can ask the developers on Firefox if they know.

**Comment by ealtenho** [comment]
Many bug reports seem to think this error has something to do with calling a method on an undefined piece of the DOM, but this seems like the most reasonable interpretation: http://www.hitthebits.com/2012/01/jquerys-html-method-and-undocumented.html
My main confusion is that in TravisCI this bug appeared between builds four and five, in which I think the only changes are reorganizations? https://github.com/angular/dom-interceptor/commit/3a6635177b4a90c8de5828996a7d13f9b16df286

**Comment by ealtenho** [comment]
Okay, my best guess is that in altering line 294 of this commit https://github.com/angular/dom-interceptor/commit/3a6635177b4a90c8de5828996a7d13f9b16df286#diff-a6cf7220a74e3838ccdaa928b0a1b91fL294 I did not understand the technique we were using with domInterceptor.listener, domInterceptor._listener, and domInterceptor.callListenerWithMessage, and that my changes have caused one of these properties to become undefined. Hence, when the patched methods attempt to call this listener, the error is produced.

**Comment by ealtenho** [comment]
We've decided to shelve this issue. The most detailed stack trace I can find of where it comes from is in the failure of the overall application in build #4: 

> [Exception... "Could not convert JavaScript argument"  nsresult: "0x80570009 (NS_ERROR_XPC_BAD_CONVERT_JS)"  location: "JS frame :: http://localhost:9876/base/node_modules/zone.js/zone.js?d0b64c0568f5205b8d22bec2f609ccf016338ad4 :: Zone.patchDefineProperty/Object.getOwnPropertyDescriptor :: line 550"  data: no]'

**Comment by ealtenho** [comment]
I think I have gotten a stack trace of where this error originates by throwing an error when the original is caught: https://github.com/angular/dom-interceptor/commit/160b703038bc90cb0fc1813b759cd585aa47a257.

**Comment by ealtenho** [comment]
https://travis-ci.org/angular/dom-interceptor/builds/28795529

The error is definitely coming from the line: 

`var desc = undefined;
    try {
      desc = Object.getOwnPropertyDescriptor(type.prototype, prop);
    }
    catch(e){}`

Enclosing this line as so in a try/catch prevents the error from occurring. It is unclear whether this has an effect on later tests or whether there are other errors caught by Travis unrelated to this bug.

**Comment by ealtenho** [comment]
Two tests that fail after adding this try/catch are for `insertBefore` and `appendChild` which are both patched on Node.prototype. I think it is most likely that Object.getOwnPropertyDescriptor(Node.prototype, prop) is causing the error.

**Comment by ealtenho** [comment]
The other current TravisCI failures are caused by .remove (which I think is due to Firefox version, see #7) and the new `patchAccessMethods` which I assume might fail because of the experimental nature of Proxies.

@btford, advice on which direction to take all of this?

**Comment by btford** [comment]
I don't know if it's worth it to keep going down this track.

Let's lock `angular-hint-dom` down on a version/branch of this library that just patches `document.getElementsBy(.+)` and doesn't worry about proxying or patching individual elements.

**Comment by ealtenho** [comment]
Alright. Sounds good. However, I do think this particular error is caused
not by patching individual elements but by the new way we are patching the
prototypes.

**Comment by ealtenho** [comment]
We went from https://github.com/angular/dom-interceptor/commit/2669e94c09f705d9ebe07937c5c11b0bc6c2e086

to the current method of patching prototypes in patchOnePrototype that throws this error on Object.getOwnPropertyDescriptor. I think the old way was throwing an error as well, hence the try/catch.

**Comment by ealtenho** [comment]
So are we not wanting to patch whole prototypes either? Just a set array of functions?

**Comment by btford** [comment]
We should patch whatever subset of things does not not involve the proxy approach. I think it also is probably too expensive to patch individual elements.

**Comment by ealtenho** [comment]
Alright. So I should figure out why our prototype patching sometimes causes errors in Firefox. And we should focus on that as our patching strategy?

**Comment by btford** [comment]
Yep. I also have another (probably bad) idea about how we could do this. Stay tuned.

**Comment by ealtenho** [comment]
Got it :)

**Comment by ealtenho** [comment]
https://travis-ci.org/angular/dom-interceptor/builds/28888683
For now tests are passing using conditional logic to not test functions that cannot be patched when Firefox blocks access to the prototypes.

**Comment by btford** [comment]
:+1:
