### ISSUE TITLE
Line numbers in Error Message: Safari

### ISSUE THREAD

**Issue by ealtenho** [angular/dom-interceptor#14]
Although the fix for #12 provides line numbers for detected manipulation in Chrome and Firefox, it does not do so for Safari where errors do not have a stack trace. Another approach would be needed for Safari: http://www.eriwen.com/javascript/js-stack-trace/

**Comment by ealtenho** [comment]
@btford we talked about a library/examples of dealing with errors in different browsers? (Or generally a more robust solution for finding line numbers other than generating errors in this situation might be applicable).

**Comment by btford** [comment]
Look at what Zone.js does.

**Comment by ealtenho** [comment]
Thanks!

https://github.com/btford/zone.js/blob/master/long-stack-trace-zone.js

Zone.js takes advantage of the fact that sometimes an exception does not have a stacktrace until it is actually thrown. In the case of Safari not yet having a stacktrace, I could throw the error to catch get the stacktrace.
