### ISSUE TITLE
triggering listener within application

### ISSUE THREAD

**Issue by ealtenho** [angular/dom-interceptor#2]
Since `Document.prototype` is patched before I patch individual html elements, getting all the elements to patch them triggers the listener despite trying to set it to the NOOP function. https://github.com/angular/dom-interceptor/blob/master/dom-interceptor.js#L186-L193

**Comment by btford** [comment]
Hm. What do you think of reversing the order: patch the individual elements, then the prototype?

**Comment by ealtenho** [comment]
That was my first thought. This does solve the unintended triggering error, but it seems to have another effect that I have not been able to debug that causes the tests on individual elements to break. But if this is the best way to approach it, I can definitely look at that again.
