### ISSUE TITLE
Proxy considered 'experimental' in Chrome

### ISSUE THREAD

**Issue by ealtenho** [angular/dom-interceptor#4]
http://stackoverflow.com/questions/23013829/chrome-javascript-proxy-object-is-not-defined

@btford 
I think that it is necessary to change a flag in Chrome to enable the harmony-reflect library to work. Is this acceptable for our project? And am I able to change a feature of Chrome while running Karma?

**Comment by ealtenho** [comment]
I was able to run these features in Karma by setting the following flag: https://github.com/angular/dom-interceptor/blob/master/karma.conf.js#L11-L15

I'm still wondering if this will be common enough for users to have it enabled?

**Comment by btford** [comment]
> I think that it is necessary to change a flag in Chrome to enable the harmony-reflect library to work

That should not be the case. This library, if I understand correctly, attempts to add the `Proxy` API to browsers that don't yet support it: https://github.com/tvcutsem/harmony-reflect

**Comment by ealtenho** [comment]
As quoted from the README: 
"The Reflect API, with support for proxies, was tested on:

Firefox (>= v4.0)
Chrome (>= v19), **with the following flag enabled: chrome://flags/#enable-javascript-harmony (copy/paste into your address-bar)**
node --harmony (>= v0.7.8)"

**Comment by btford** [comment]
:frowning:

**Comment by ealtenho** [comment]
https://github.com/angular/dom-interceptor/commit/160b703038bc90cb0fc1813b759cd585aa47a257

**Comment by ealtenho** [comment]
We've decided to use other strategies since proxies are not yet uniformly supported.
