### ISSUE TITLE
Best effort manipulation detection

### ISSUE THREAD

**Issue by ealtenho** [angular/dom-interceptor#6]
@btford Given the current state of proxy implementation, and the errors currently received from patching individual DOM elements. I'm wondering if a best effort detection could be to just rely on the methods that can be patched via the prototypes? In order to change an element, it is fairly likely that a method like getElementById will be called in order to get the element.

Is this a high enough level of accuracy, or should we still focus on trying to improve the patching of individual elements?

**Comment by btford** [comment]
>  a best effort detection could be to just rely on the methods that can be patched via the prototypes?

Yep, sounds reasonable.

**Comment by ealtenho** [comment]
Since some prototype manipulation, and therefore testing, is not supported in Firefox, I will detect conditionally whether that manipulation will cause errors and stop my testing at that point.

**Comment by ealtenho** [comment]
https://github.com/angular/dom-interceptor/commit/80cadcafbfe0e5386a5c17d62a3c907ce667a48e
@btford 
First iteration conditional testing. This is still difficult to test locally as my local Firefox tests are all green. However, this logic fails to stop the tests remotely.

**Comment by ealtenho** [comment]
Final evaluation: patching `Document`, `Element`, and `Node` prototypes covers all the `DOM` APIs that we originally identified should be detected in order to alert developers of `DOM` manipulation. Other methods for patching individual elements or using proxies are left in the library but are not used to implement the `manipulationListener` that is the overall product of the library that is for instance used by `hintDOM`.
