### ISSUE TITLE
Firefox version and .remove() detection?

### ISSUE THREAD

**Issue by ealtenho** [angular/dom-interceptor#7]
In my `.travis.yml`, I specify Firefox 29 as my browser, but I notice in the testing logs that Firefox 19.0.0 is listed. https://travis-ci.org/angular/dom-interceptor/builds/28795529

I'm also receiving an error that .remove() is not a method. I believe before this error may have been covered up by also having JQuery installed. 

Is this a reasonable diagnosis of this error?

**Comment by ealtenho** [comment]
I notice that the travis build has a note that `sudo, services, addons, setuid and setgid have been disabled`. Since the specification of firefox 29 is an addon. I'm not sure why this would be disabled, or if this is referring to the same addon?

**Comment by ealtenho** [comment]
@btford 
TODO: set up sauce labs in order to use latest version of Firefox.
Pair tomorrow afternoon?

**Comment by ealtenho** [comment]
Rather than basing my sauce labs set up off of Angular's strategy that depends on grunt, I found Karma's reference on how to configure a sauce labs launcher:
https://github.com/saucelabs/karma-sauce-example/blob/master/karma.conf-ci.js
I'm still having difficulties getting this to work:
https://travis-ci.org/angular/dom-interceptor
This error looks like a permissions error? So maybe something about the username and access key?

**Comment by ealtenho** [comment]
@btford any information on permissions for sauce labs?

**Comment by ealtenho** [comment]
@btford Did you have a commit or PR with the new sauce labs configuration we worked on yesterday?

**Comment by btford** [comment]
Yes. I'm still trying to fix the issue WRT credentials. I'll submit a PR when I get a chance.

**Comment by btford** [comment]
See #9; please review and merge that when you have the chance

**Comment by ealtenho** [comment]
Merged PR from #9 https://github.com/angular/dom-interceptor/commit/dd6d12bc5350f300ba95949d815e700dbe3c0c20

And after wrangling with Safari in various commits, Travis is now passing using SauceLabs!
https://travis-ci.org/angular/dom-interceptor/builds/30128377

**Comment by btford** [comment]
Great work!
